### ISSUE TITLE
Can't build with latest GHC 7.6 and Cabal

### ISSUE THREAD

**Issue by jwiegley** [OlafChitil/hat#2]
The very latest Hat resolved most of the cabal and compilation errors, but I'm still stuck on this one:

```
[36 of 38] Compiling Hat.Directory    ( Hat/Directory.hs, dist/build/Hat/Directory.o )

Hat/Directory.hs:274:6:
    Couldn't match type `time-1.4.0.1:Data.Time.Clock.UTC.UTCTime'
                  with `ClockTime'
    Expected type: Prelude.IO ClockTime
      Actual type: Prelude.IO time-1.4.0.1:Data.Time.Clock.UTC.UTCTime
    In the return type of a call of `Directory.getModificationTime'
    In the third argument of `T.fromIO', namely
      `(Directory.getModificationTime
          (toString kgetModificationTime z1getModificationTime))'
    In the expression:
      (T.fromIO fromClockTime)
        kgetModificationTime
        (Directory.getModificationTime
           (toString kgetModificationTime z1getModificationTime))
Failed to install hat-2.7.0.9
cabal: Error: some packages failed to install:
hat-2.7.0.9 failed during the building phase. The exception was:
ExitFailure 1
```
